services:
  kitsune:
    image: dovakiin0/kitsune-v2:latest
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=http://kitsune:3000
      - NEXT_PUBLIC_PROXY_URL=http://proxy:8080

  proxy:
    image: dovakiin0/m3u8-proxy:latest
    ports:
      - "8080:8080"
    environment:
      - host=0.0.0.0
      - port=8080
      - public_url=http://proxy:8080
